apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-worker
  namespace: playwright-test
spec:
  completions: 4
  parallelism: 4  
  ttlSecondsAfterFinished: 300   # Pods bleiben 5 Minuten nach Job bestehen
  template:
    spec:
      volumes:
        - name: queue
          emptyDir: {}
        - name: reports
          emptyDir: {}    
      containers:
        - name: playwright
          image: ghcr.io/thanhtrungtran-testautomation/portfolio-playwright/app:IMAGE_TAG
          #imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: queue
              mountPath: /queue 
            - name: reports
              mountPath: /reports         
          # Environment Variables für URLs
          env:
            - name: PLAYWRIGHT_baseUrl
              value: "http://localhost:3000"   # Base URL für Tests
            - name: HOME
              value: "/root"
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']           
          command:
            - sh
            - -c
            - |
              echo "Runner index: $JOB_COMPLETION_INDEX"
              #echo "Pod index: $HOSTNAME"
              npm ci
              # App im Hintergrund starten
              node demo-app/server.js &
              # Warten bis App auf localhost:3000 bereit ist
              npx wait-on http://localhost:3000
              echo "Running tests on pod: $HOSTNAME"              
              INDEX=${JOB_COMPLETION_INDEX}
              TOTAL=4

              SHARD=$((INDEX+1))

              echo "Running shard $SHARD of $TOTAL"

              REPORT_DIR=/reports/shard-$SHARD
              mkdir -p $REPORT_DIR

              if [ "$SHARD" = "1" ]; then
                npx playwright test --shard=$SHARD/$TOTAL --reporter=html --report-dir=$REPORT_DIR
              else
                npx playwright test --shard=$SHARD/$TOTAL --report-dir=$REPORT_DIR
              fi
      restartPolicy: Never
  backoffLimit: 1